import Vue from 'vue'
import { Button, Form, FormItem, Input, Message, Container, Header, Aside,Main, Footer,Menu ,MenuItem,MenuItemGroup,Submenu,Carousel,CarouselItem,PageHeader,link,Backtop,Row,Col,Card,Checkbox,CheckboxGroup,Avatar,Dropdown,DropdownMenu,DropdownItem,Badge,Upload,tag,Select,Option} from 'element-ui'


Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(PageHeader)
Vue.use(link)
Vue.use(Backtop)
Vue.use(Col)
Vue.use(Row)
Vue.use(Card)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Avatar)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Dropdown)
Vue.use(Badge)
Vue.use(Upload)
Vue.use(tag)
Vue.use(Select)
Vue.use(Option)
Vue.prototype.$message = Message